### ISSUE TITLE
Error formatting file: Vim(let):E484: Can't open file /tmp/vC6awwI/8

### ISSUE THREAD

**Issue by sfraczek** [google/vim-codefmt#106]
Hi,

how can I change the tmp directory? I get this error
`Error formatting file: Vim(let):E484: Can't open file /tmp/vC6awwI/8` when truing to `:FormatCode`.

**Comment by sfraczek** [comment]
Ok I found how to change it. Wrote at the beginning of `~/.vimrc` this: `let $TMPDIR = "/home/sfraczek/.vim-tmp"`

but this didn't fix the problem...
`Error formatting file: Vim(let):E484: Can't open file /ec/fm/disks/nrv_algo_home01/sfraczek/.vim-tmp/viGs461/2`

do you know what might be causing this and how to fix it?

**Comment by dbarnett** [comment]
Looks like a dupe of #86. See discussion there and the bug I filed for it in the library, google/vim-maktaba#215, and try the suggested "SetUsableShellRegex" workaround there to see if it helps get you unstuck. If you can post your findings we might be able to make some progress towards getting it compatible with Win 10.

**Comment by dbarnett** [comment]
I'll close this one for now, but please comment/reopen if you don't think it's the same issue after all.

**Comment by sfraczek** [comment]
Hi, 
thanks for reply.

I think it's a different issue because I'm having this problem on linux not on windows.
 
This `call maktaba#syscall#SetUsableShellRegex('\v^/bin/sh|cmd|cmd\.exe|command\.com$')` didn't help. 
I have this plugin work on my desktop ubuntu 16.04.5 but I can't get it to work on a server ubuntu 16.04.3. 
When I look at the directory pointed by the error like: `Error formatting file: Vim(let):E484: Can't open file /tmp/vv5XWOu/2`
it exists but the file doesn't. I can create files there myself.
```
ls -al /tmp/vv5XWOu/
total 356
drwx------  2 sfraczek kmem   4096 Oct 18 00:42 .
drwxrwxrwt 63 root     root 356352 Oct 18 00:41 ..
```

I tried to follow the windows10 debugging calls from that issue #86 and here are the results:
`:call maktaba#buffer#Overwrite(1, line('$'), [])` makes my current buffer empty
`:echo has('job')` responds with 1
`:call maktaba#syscall#Create(['cat']).WithStdin('').Call()` shows me the same error.
`:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])` shows no error.
`call maktaba#syscall#SetVimjobDisabledForTesting(1)` doesn't help.

**Comment by dbarnett** [comment]
If this is in long-running vim sessions, vim has known issues where it doesn't verify tmp directories it previously created still exist, and obviously tmp directories can disappear without warning for various reasons. It sounds like you are saying you can reproduce consistently though, right?

**Comment by sfraczek** [comment]
yes, it happens all the time, not just old sessions.

**Comment by manikanta226** [comment]
Hi, I'm also facing the same issue. 
if I enter this command `:FormatCode clang-format` . getting error as `Error formatting file: Vim(let):E484: Can't open file /tmp/vVJhj2Y/1` .

I Updated the add this line to my vimrc also `let $TMPDIR = "/usr2/c_sai/.vim-tmp"` But still not working.

colud  you please tell me what are the dependencies ?

**Comment by dbarnett** [comment]
What do you get when you execute
```vim
:verbose set shell?
```
?

I suspect it's still the same basic error as google/vim-maktaba#215, which you'd see if `/bin/sh` doesn't exist as an executable shell on your system.

If `:call system('ls')` works without error, try executing this in your vim session:
```vim
call maktaba#syscall#SetUsableShellRegex('\v.*')
```
and then retry to see if it still errors out.

**Comment by sfraczek** [comment]
I'm afraid I have lost access to that server where I had this problem so I can't confirm it now. Thank you very much for revisiting it! :) I will close the issue now.

**Comment by jgodden** [comment]
Not sure if it's ok to add a comment to a closed call, so apologies if so.
I was having this issue, and found that opening a Perl file works if logged in as standard user, but gets this error if using a nologin shell (dbarnett's suggestion to check). As you can still sudo to run a bash shell as a nologin user, you should still be able to edit perl files as this user.
Should I open another ticket to get resolved?

**Comment by dbarnett** [comment]
Either way. New issue w/ thorough details to reproduce would be helpful to back up and clarify exactly what you've tried so far in your case.

I tried using `sudo` to impersonate a nologin user and didn't get any error from `:call maktaba#syscall#Create(['cat']).WithStdin('').Call()` which supposedly did error out for sfraczek. It would be especially helpful to know vim version, output of `:verbose set shell?`, and confirm in this case that:
```vim
:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])
```
shows no error but that:
```vim
:call maktaba#syscall#Create(['cat']).WithStdin('').Call()
```
does show an error.

**Comment by jgodden** [comment]
I have the following version of vim installed:

$ vim -h
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 13 2020 16:13:17)

From /etc/passwd:
fred:x:1542:1542::/home/fred:/bin/bash
mqm:x:1001:1205::/var/mqm:/sbin/nologin

From a vim session editing a perl file:

For user 'fred' (no error opening):
 :verbose set shell?
 shell=/bin/bash
:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])
(no error)
:call maktaba#syscall#Create(['cat']).WithStdin('').Call()
E117: Unknown function: maktaba#syscall#Create

For user 'mqm'
error when opening perl file:
Error detected while processing /usr/share/vim/vim74/ftplugin/perl.vim:
line   50:
E484: Cannot open file /tmp/vzRqOFT/0
Error detected while processing function <SNR>6_LoadFTPlugin:
line   17:
E170: Missing :endfor
Error detected while processing function <SNR>5_FTpl:
line   10:
E171: Missing :endif

:verbose set shell?
shell=/sbin/nologin
:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])
E484: Cannot open file /tmp/vzRqOFT/8
:call maktaba#syscall#Create(['cat']).WithStdin('').Call()
E117: Unknown function: maktaba#syscall#Create

Please let me know if I can add any more info that may be of use.

**Comment by dbarnett** [comment]
Thanks! I followed up there: I think that issue is unrelated. I am still interested in getting more findings if anyone runs into cases where `maktaba#Syscall#` stuff fails with E484 but `system()` succeeds.

**Comment by malcolmr** [comment]
Note that for long-running Vim sessions specifically, Vim 8.2.0711 includes a change to lock the Vim temporary directory so that it's no longer reaped (in most cases) while Vim is still running.
