### ISSUE TITLE
Link to vroom is incorrect

### ISSUE THREAD

**Issue by farisachugthai** [google/vim-codefmt#109]
Hey guys. In the README under the section 'Creating A New Formatter', a link exists to vroom that points to 
https://github.com/google/vim-vroom

But the repo is actually at https://github.com/google/vroom, so the user gets 404ed if they follow it. Not a big deal, but I just wanted to give you guys a heads up!

**Comment by fowles** [comment]
Faris~

Fixed.  Thanks for the heads up.

Matt

**Comment by farisachugthai** [comment]
No problem! I'm gonna go ahead and close this
