### ISSUE TITLE
js-beautify fommat cannot work

### ISSUE THREAD

**Issue by lsff** [google/vim-codefmt#111]
Error running: js-beautify -f - --type js
![image](https://user-images.githubusercontent.com/2011181/50554377-37d88100-0cf4-11e9-94e6-73c4baa4348a.png)

**Comment by malcolmr** [comment]
I think this is a bug in js-beautify, not vim-codefmt. According to the documentation at https://www.npmjs.com/package/js-beautify, passing `-f -` should make jsbeautify format stdin to stdout. However, it looks like that doesn't work on Windows for some reason.

**Comment by malcolmr** [comment]
I've filed a js-beautify issue (above), so I'm going to close this. I'll reopen if it turns out there's something that we can change locally.

**Comment by bitwiseman** [comment]
@lsff  
What version of js-beautify do you have installed?

**Comment by Qs-F** [comment]
I fixed related issue on js-beautify and merged, so now this can be closed, I think!

**Comment by Qs-F** [comment]
I fixed related issue on js-beautify and it was merged. Now you can get changes by updating js-beautify. And so, this issue can be closed, I tihnk.

**Comment by dbarnett** [comment]
Thanks @Qs-F!

@lsff please let us know if you update js-beautify and still have issues.

**Comment by bitwiseman** [comment]
@lsff @dbarnett @Qs-F 
You can test this by installing 1.8.10-beta2.
