### ISSUE TITLE
Error formatting file: ERROR(ShellError)

### ISSUE THREAD

**Issue by afezeria** [google/vim-codefmt#112]
when I save html file,it turns out:
```
Error formatting file: ERROR(ShellError): Error running: js-beautify -f - --type html
Unable to open path "/home/zodal/-"
Run `js-beautify -h` for help.
```
I think this error may be due to line 43 of vim-codefmt/autoload/codefmt/jsbeautify.vim
```let l:cmd = [s:plugin.Flag('js_beautify_executable'), '-f', '-']```
When I change it to this:
```let l:cmd = [s:plugin.Flag('js_beautify_executable'), '-f', expand('%:p')]```
It works.

I don't know if it's my problem. Because I'm running it in win10 subsystem for Linux

**Comment by malcolmr** [comment]
I'm pretty sure this is the same as #111, which is fixed in newer versions of js-beautify.
