### ISSUE TITLE
Not an editor command: prettier

### ISSUE THREAD

**Issue by Eksapsy** [google/vim-codefmt#117]
## Error
```
Error detected while processing FileType Auto commands for "javascript":
E492: Not an editor command: prettier                                   
```
## Config & Setup
**.vimrc**
```vimrc
augroup autoformat_settings
    autocmd Filetype javascript prettier
augroup END
```
**Plugins**
```
Plugin 'VundleVim/Vundle.vim'       
Plugin 'Valloric/YouCompleteMe'     
Plugin 'scrooloose/nerdtree'        
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'leafgarland/typescript-vim' 
Plugin 'Qurami/tsuquyomi'           
Plugin 'tomasiser/vim-code-dark'    
Plugin 'airblade/vim-gitgutter'     
Plugin 'ctrlpvim/ctrlp.vim'         
Plugin 'tacahiroy/ctrlp-funky'      
Plugin 'tpope/vim-fugitive'         
> Plugin 'google/vim-maktaba'         
> Plugin 'google/vim-codefmt'         
> Plugin 'google/vim-glaive'          
Plugin 'majutsushi/tagbar'          
Plugin 'ternjs/tern_for_vim'        
Plugin 'pangloss/vim-javascript'    
```
## What have I done
To make sure this is not an issue of non-existant **binary** or **node_module**, I installed **prettier** on both **local npm** and **global npm**. 
```
npm install -g prettier
npm install --save-dev --save-exact prettier
```
I am not sure though if you integrate this already in the plugin in some vim-y way, which would mean that I don't have to install it.
Either way, it didn't seem to work.

**Comment by Eksapsy** [comment]
I should have looked more carefully, I forgot to put `AutoFormatBuffer` in between `javascript prettier`.

**Comment by malisoft** [comment]
I'm still having the same problem
```
augroup autoformat_settings 
    autocmd Filetype javascript AutoFormatBuffer prettier
augroup END
```
and my plugin

```
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install --frozen-lockfile --production',
  \ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'svelte', 'yaml', 'html'] }

```

**Comment by dbarnett** [comment]
@malisoft Are you sure it's exactly the same problem? `E492: Not an editor command: prettier`

I'd also try removing that `'for'` option from your `:Plug` command and see if whatever error you're seeing goes away, since vim-plug maintainers now [discourage that option](https://github.com/junegunn/vim-plug/wiki/faq#when-should-i-use-on-or-for-option) and it can lead to strange loading problems.

**Comment by agriffis** [comment]
@malisoft Are you sure you want to be using both `vim-codefmt` and `vim-prettier`? They attempt to solve the same problem and they'll probably step on each other's toes.

**Comment by dbarnett** [comment]
Oh! Yes, I assume the actual error you're seeing is `E492: Not an editor command: AutoFormatBuffer` and that's because you haven't actually installed this plugin which defines the AutoFormatBuffer command.
