### ISSUE TITLE
Configuration of google_java_executable does not allow environment variable in Path

### ISSUE THREAD

**Issue by dacarey** [google/vim-codefmt#118]
When using the **Google Java code** formatter with **vim-codefmt** i had wanted to configure the path using an environment variable. _For example:-_
```
Glaive codefmt google_java_executable="java -jar $HOME/dotfiles/vim/google-java-format-1.7-all-deps.jar"
```
However when subsequently running the **:FormatCode** command in a vim editing session, the command fails with the following error:-
```
Error formatting file: ERROR(ShellError): Error running: java -jar '$HOME/dotfiles/vim/google-java-format-1.7-all-deps.jar' --lines 1:7 -
```
The low-level cause is actually in the **s:SoftShellEscape** in **syscall.vim** in the associated **vim-maktaba** plugin.  It escapes the path with ' characters.  Look closely and this can be seem in the error message above.

I can think of the following solutions for this:-
1. Raise an issue in **vim-maktaba** to exclude the $ character as a cause for escaping.  It is unclear to me why this isn't allowed but there may be a use case that i'm unaware of.
2. Raise an issue in **vim-maktaba** to make the regex pattern configurable ( similar to the shell config option)
3. Recode the google java code formatter to build the command line in a different way.

1.  or 2. seem preferable but any thoughts otherwise?

**Comment by dbarnett** [comment]
An easy workaround would be to expand when setting the flag:
```viml
Glaive codefmt google_java_executable=`expand('java -jar $HOME/dotfiles/vim/google-java-format-1.7-all-deps.jar')`
```

There's already some customization going on at the codefmt level trying to carefully split the value on unescaped strings before passing to maktaba (https://github.com/google/vim-codefmt/blob/fc45c30907106801f0bf443a9fa20300fc6ce100/autoload/codefmt/googlejava.vim#L53). maktaba tries to be shell-agnostic and not handle clever things like environment variable substitution. I'm a little leery of just making it silently handle more and more corner cases, but for this use case of passing a literal command to flags maybe there could be a special helper function to safely extract to a command with expansions and stuff so codefmt wouldn't need any of this special-case splitting and stuff.

**Comment by dacarey** [comment]
My bad,  I should have read the Glaive documentation more closely.

Thanks very much.  That is an easy workaround and the explanation makes perfect sense regarding keeping maktaba shell agnostic.
