### ISSUE TITLE
Support clang-format -cursor option to preserve cursor position while formatting

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#13]
Newer versions of clang-format support a `-cursor=<uint>` option to precisely maintain cursor position from before formatting and output a JSON structure as the first line of output indicating the final cursor position after formatting.

We should add support to codefmt to hook into this mechanism and precisely preserve the cursor position when formatting with clang-format. If lots of users are still using an older clang-format version that doesn't accept the `-cursor` flag, we could have a flag to control whether to use the cursor preservation and/or detect support by reading the version number from `clang-format --version`.

**Comment by malcolmr** [comment]
We should also parse the "IncompleteFormat" true/false value that's returned by (newer) `clang-format` that indicates that only a partially-formatted result was written (due to a parse error).

**Comment by fowles** [comment]
Fixed in c426e4337314ad3569d815ba50a8173dae195d46
