### ISSUE TITLE
Associate clang-format formatter with C and Obj-C

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#15]
In clang-format's help, it calls itself "a tool to format C/C++/Obj-C code", but the current AppliesToBuffer check on the clang-format formatter only checks for cpp, proto, and javascript filetypes.

We should enable it as a default formatter for filetypes c, objc, and objcpp so that if people use `:FormatCode` on these filetypes with no explicit formatter, they will get code formatted with clang-format instead of seeing `Not available. codefmt doesn't have a default formatter for this buffer`.

**Comment by Kashomon** [comment]
Is this a trivial change to the list of filetypes?

**Comment by dbarnett** [comment]
Yeah, I think I reported the feature request instead of implementing it directly is I wanted a sanity check that it gives good results from someone who uses C and Obj-C more, and also to ensure that enabling it by default won't cause headaches for googlers.
