### ISSUE TITLE
Formatting for JSP files.

### ISSUE THREAD

**Issue by 287mdsahil** [google/vim-codefmt#151]
Is there a way to format JSP files with this?
I tried formatting with js-beautify but failed.

**Comment by dbarnett** [comment]
If you didn't find an existing issue searching for JSP (https://github.com/google/vim-codefmt/issues?q=is%3Aissue+JSP) then you should just go through the "Request new formatter" option and fill out whatever of that info you're able. I can dedupe any existing issues you may have missed.
