### ISSUE TITLE
when I use formatcode clang-format it shows such errors

### ISSUE THREAD

**Issue by zjbbuaa** [google/vim-codefmt#155]
error detected while processing function <SNR>38_FormatBufferAndSetRepeat..codefmt#FormatBuffer..<SNR>43_GetFormatter ..<SNR>43_IsAvailable..12..codefmt#formatterhelpers#ResolveFlagToArray:

**Comment by dbarnett** [comment]
Is that the whole error you saw? That's just the call stack trace but after the colon it should say what the error was.

It's something about the values you have configured for flags but I don't know which flag or what value it had from just that line of error output. If you can make sure you have https://github.com/google/vim-glaive installed and execute `:Glaive codefmt` in your vim and share the output, that could give some clues too.

**Comment by zjbbuaa** [comment]
when I execute :Glavie codefmt 
![image](https://user-images.githubusercontent.com/20664050/88513146-59a60100-d01a-11ea-9dfc-c4635b641295.png)
It means it is ok with clang-format
but when I execute  format-code clang-format
![image](https://user-images.githubusercontent.com/20664050/88513300-9e319c80-d01a-11ea-8a56-530607c9a214.png)

**Comment by zjbbuaa** [comment]
can any one can help me?

**Comment by dbarnett** [comment]
Ah, looks like you're running a fairly old version of vim older than 7.4.1546. #158 should fix that, and improve error messages for any other similar errors that may come up.
