### ISSUE TITLE
Error: Not available. codefmt doesn't have a default formatter for this buffer.

### ISSUE THREAD

**Issue by kosich** [google/vim-codefmt#16]
[The announcement](http://google-opensource.blogspot.ru/2015/01/format-code-easy-way-with-codefmt.html) claims this plugin supports cpp & js natively.
so after installing with vundle ( as provided in the readme file )
when I try to `:FormatCode` on .cpp or .js files I get following error:
`Not available. codefmt doesn't have a default formatter for this buffer.`

What I am missing? Should one use VAM or install any additional plugins? Thanks in advance.

**Comment by fowles** [comment]
Can you post a link to your .vimrc?

**Comment by kosich** [comment]
https://github.com/kosich/dotfiles/blob/master/vim/.vimrc
:flushed:

**Comment by fowles** [comment]
Did you remember to run :BundleUpdate?

**Comment by fowles** [comment]
Also do you have clang-format installed?

**Comment by kosich** [comment]
Ye, updated.
[this one](https://github.com/rhysd/vim-clang-format)?

**Comment by fowles** [comment]
No, http://clang.llvm.org/docs/ClangFormat.html 

Try typing `:FormatCode clang-format` in vim.  That should print the setup instructions if it doesn't like the formatter that you have.

**Comment by dbarnett** [comment]
If typing `clang-format --version` on the command line doesn't work, then codefmt won't be able to use it without more configuration. We should give more detailed setup instructions in the codefmt help and possibly change that message to point to more details.

**Comment by fowles** [comment]
I am in process fixing the error message

**Comment by kosich** [comment]
as @fowles pointed, I haven't had clang-format at all: now downloading/installing it. Will report on successful resolving. Thanks!

@dbarnett , ye, would be nice to add that to readme~~, cz there are dumb guys like me, you know~~  =)

**Comment by kosich** [comment]
Though `:FormatCode clang-format` gave proper error:
`Formatter "clang-format" is not available. Setup instructions: Install clang-format from http://clang.llvm.org/docs/ClangFormat.html and configure the clang_format_executable flag`

**Comment by kosich** [comment]
Installed successfully. But since I'm no good in VimL, couldn't figure out how to properly set up the `clang_format_executable` option. So I had to use Glave:
`Glaive codefmt clang_format_executable='/usr/bin/clang-format-3.5'`

Thanks, @fowles !

Guys, could you provide more detailed install/setup instructions in the README ?

**Comment by dbarnett** [comment]
> But since I'm no good in VimL, couldn't figure out how to properly set up the clang_format_executable option. So I had to use Glaive

Glaive is the way to properly set up clang_format_executable. Did you get the impression from somewhere there was a better way? Just wondering if we need to do more to clarify that point.

**Comment by kosich** [comment]
Hey, sorry for the late reply...
> Did you get the impression from somewhere there was a better way?

If you mean installation guide, then just make it clear in the readme, that:
1. This plugin requires a tool, like `clang-format` to work
2. By default it uses `clang-format`, which should be available via that alias

And

1. If _you_ haven't got `clang-format`, you may download it from [here](http://clang.llvm.org/docs/ClangFormat.html)
2. configure `Glaive codefmt clang_format_executable='/usr/bin/clang-format-3.5'`

( just humanize that, cz I'm kinda sleepy atm )

Also, everyone would be glad to see that clang-format is configurable globally and locally:
http://clang.llvm.org/docs/ClangFormatStyleOptions.html

Anyways, thanks for the replies and the plugin!

**Comment by dbarnett** [comment]
K, #21 is adding friendly explanations for how each formatter works into vroom files. I probably want to sprinkle some quick pointers in the README and help files and point people to those vroom files for details.
