### ISSUE TITLE
Incorrect maktaba version read

### ISSUE THREAD

**Issue by TamaMcGlinn** [google/vim-codefmt#168]
**Describe the bug**
At vim startup, codefmt complains that I have maktaba version 0.0.1 installed, but I actually have 1.16.0 as evidenced by the addon-info.json in maktaba.

**To Reproduce**
Unfortunately, when I made the following minimal reproducer, it fails with a different error message; now maktaba complains that codefmt doesn't exist with `Exception not caught: ERROR(NotFound): Plugin codefmt`. Minimal vimrc using Dein:
```
" Required:
set runtimepath+=~/vimscripts/dein/repos/github.com/Shougo/dein.vim
call dein#begin('~/vimscripts/dein', ['~/vimrc/plugins.vim'])

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')
call dein#add('google/vim-maktaba')
call dein#add('google/vim-codefmt')
" Required:
call dein#end()

let dein#enable_notification = 1

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
```

**OS (version)**
Linux 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dbarnett** [comment]
Hmm, what do
```vim
:echo maktaba#VERSION
```
and
```vim
:echo maktaba#Maktaba().AddonInfo()
```
output for you?

Do you have a built-in `json_decode` function, and if so what does
```vim
:echo json_decode(join(readfile(maktaba#Maktaba().location . 'addon-info.json'), "\n"))
```
output for you?

**Comment by TamaMcGlinn** [comment]
Hmmm. that indicates 0.0.1 in both cases.

**Comment by TamaMcGlinn** [comment]
I think the problem is that dein puts all the plugins together in the same directory as a speed optimization, but that means bazel's and maktaba's addon-info.json need to occupy the same space. Dein should check if any plugins use the same files, and if so, create an additional directory so that both can be used.

**Comment by dbarnett** [comment]
Aha, overwriting addon-info.json files would definitely explain it. It looks like dein.vim does [provide a `{'merged': 0}` option](https://github.com/Shougo/dein.vim/issues/153#issuecomment-266404119) to keep plugins in separate directories, but AFAICT by default it'll just silently overwrite one plugin's files with another.
