### ISSUE TITLE
Error detected while processing /usr/share/vim/vim74/ftplugin/perl.vim

### ISSUE THREAD

**Issue by jgodden** [google/vim-codefmt#179]
**Describe the bug**
Error reported when opening a perl file with vim as nologin user. After pressing ENTER, continues to open file successfully.

**To Reproduce**
As a user defined with /bin/nologin, open perl file using vim. Content of .vimrc not relevant for this issue
Get error:
`Error detected while processing /usr/share/vim/vim74/ftplugin/perl.vim:`
`line   50:`
`E484: Cannot open file /tmp/vaX97Jm/0`
`Error detected while processing function <SNR>6_LoadFTPlugin:`
`line   17:`
`E170: Missing :endfor`
`Error detected while processing function <SNR>5_FTpl:`
`line   10:`
`E171: Missing :endif`
`Press ENTER or type command to continue`

**Expected behavior**
The file to open without error

**OS (version)**
Linux 3.10.0-1160.6.1.el7.x86_64

I have the following version of vim installed:

$ vim -h
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 13 2020 16:13:17)

From /etc/passwd:
`fred:x:1542:1542::/home/fred:/bin/bash`
`mqm:x:1001:1205::/var/mqm:/sbin/nologin`

From a vim session editing a perl file:

As user 'fred' (no error opening):
`:verbose set shell?`
gives
`shell=/bin/bash`

`:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])`
gives no error

`:call maktaba#syscall#Create(['cat']).WithStdin('').Call()`
gives
`E117: Unknown function: maktaba#syscall#Create`

As user 'mqm', get error as reported above.
`:verbose set shell?`
gives
`shell=/sbin/nologin`

`:call system(printf('cat > %s 2> %s', tempname(), tempname()), [])`
gives
`E484: Cannot open file /tmp/vaX97Jm/4`

`:call maktaba#syscall#Create(['cat']).WithStdin('').Call()`
gives
`E117: Unknown function: maktaba#syscall#Create`

**Comment by dbarnett** [comment]
Ah, so by "opening a Perl file" you meant just loading a file and triggering the vim ftplugin. Any bug with that or with `:call system()` would be vim bugs and not issues with our plugins. You could report at http://github.com/vim/vim/issues and see if they could add some error handling to make the experience slightly better.

I'm going to close this issue from the codefmt perspective, but definitely let us know any findings if you do run into cases where the `system()` commands succeed while `maktaba#syscall#` stuff fails with E484.

**Comment by jgodden** [comment]
ok, thanks @dbarnett
