### ISSUE TITLE
dartfmt is deprecated

### ISSUE THREAD

**Issue by chengen** [google/vim-codefmt#190]
**Describe the bug**
The `dart format` command replaces `dartfmt`.
Dart SDK version: 2.16.1 already removed `dartfmt` command line tool. 
I try to use alias as a work around, but not working. 
alias dartfmt='dart format -o show' 

thanks!

**Comment by dbarnett** [comment]
Shell alias is completely ignored in vim syscalls IIRC. Did you try setting dartfmt_executable instead? Something like `Glaive codefmt dartfmt_executable='dart format -o show'`? I can't remember if we set that one up to split spaces properly yet, so that might just give an error about the spaces if not.

**Comment by chengen** [comment]
> That's... annoyingly quick, as deprecations go.
> 
> I think we might want to basically replicate the functionality from [dart-lang/dart-vim-plugin#125](https://github.com/dart-lang/dart-vim-plugin/pull/125), which checks whether `dart` exists, then does a version match on the output of `dart --version`, and uses `dart format` if the version is >= 2.14.

Thank you  malcolmr,   that would be great if codefmt solve this by check dart version.

**Comment by dbarnett** [comment]
Yes, that should work if the `dartfmt_executable` override doesn't. We should still make sure that override works and follow up about the version check.

I'd suggest to minimize overhead for the new case by always attempting `dart format` first, then falling back to a version check and `dartfmt` for whatever error cases suggest the new version is missing.
