### ISSUE TITLE
Error installing codefmtlib

### ISSUE THREAD

**Issue by amittal** [google/vim-codefmt#20]
Hi

I am getting this error while trying to do use :FormatCode in my C++ code.

ERROR(NotFound): Library "codefmtlib" could not be installed, because there are no library installers registered with maktaba

Here's my vimrc

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'google/vim-maktaba'
Plugin 'google/vim-glaive'

Plugin 'google/vim-codefmtlib'
Plugin 'google/vim-codefmt'

call vundle#end()

" Now we can turn our filetype functionality back on
filetype plugin indent on

Can someone please help me identify the issue.
Thanks

**Comment by dbarnett** [comment]
Sounds like #6. Could you try updating google/vim-maktaba if you haven't in the last day or two?

**Comment by amittal** [comment]
Thanks. That worked.

**Comment by dbarnett** [comment]
@fowles Think it's worth a note in the README to make sure to update maktaba first? I don't know how many people will already have an existing version of maktaba installed, but those who do probably won't all find closed issues here.

**Comment by fowles** [comment]
Certainly wouldn't hurt.
