### ISSUE TITLE
Switch from codefmtlib to maktaba#extension

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#32]
Maktaba now has a built-in `maktaba#extension#` mechanism that's designed to replace codefmtlib and similar plugins. We should switch codefmt to use it and deprecate the codefmtlib repo.

**Comment by malcolmr** [comment]
Assuming that the only caller of codefmtlib's `AddDefaultFormatter()` and `GetFormatter()` is codefmt itself (which seems reasonable), we can probably achieve this by 'simultaneously' changing codefmt and replacing codefmtlib with a very small VimScript:

```viml
function! codefmtlib#AddFormatter(formatter) abort
  call maktaba#extension#GetRegistry('codefmt').AddExtension(a:formatter)
endfunction
```

**Comment by dbarnett** [comment]
Heh, didn't think about migration complications. Yeah, that should be fine, and if anyone reports they're missing formatters because they got one update without the other, they'll just need to update both and restart vim.
