### ISSUE TITLE
codefmt CI tests should checkout a specific version of Maktaba

### ISSUE THREAD

**Issue by malcolmr** [google/vim-codefmt#35]
codefmt depends upon (and documents) a minimum version of Maktaba (currently 1.1; soon to be 1.9). The codefmt CI tests should check out that version, not HEAD, so that we can make sure that we can work with the version we've specified.

(Locally, codefmt will use whatever's available locally, which _will_ probably be HEAD, so I don't think we'd be losing any test coverage by doing that.)

Unless anyone objects, I'd like to:
- Push tags to `vim-maktaba` covering the releases we've made.
- Change codefmt's `.travis.yml` to clone a named Maktaba release.

(I think it's okay to keep depending on Glaive HEAD, since that's not really undergoing much development, and is _only_ needed for the tests.)

**Comment by dbarnett** [comment]
SGTM.

You plan to test both versions, right? If we had to choose between versions to test, HEAD is probably more generally useful since that's closer to what most users will get. But AFAIK testing both in Travis is not hard.

**Comment by malcolmr** [comment]
I guess we could test both? I was only planning on testing 1.9 (or whatever we require), since I was expecting people to run the tests locally against HEAD.

Do you mean adding a separate `matrix` entry for Maktaba-HEAD, or something else? (Sorry if this is a dumb question; I'm not that familiar with Travis.)

**Comment by dbarnett** [comment]
Yeah, a separate matrix entry is what I had in mind. Dunno if we need to test both vim and neovim with both versions, but doesn't matter much either way.
