### ISSUE TITLE
Registering external formatters immediately after load breaks codefmt

### ISSUE THREAD

**Issue by malcolmr** [google/vim-codefmt#37]
In `autoload/codefmt`, we have:

```VimL
let s:plugin = maktaba#plugin#Get('codefmt')
let s:plugin_root = expand('<sfile>:p:h:h:h')
let s:registry = s:plugin.GetExtensionRegistry()

call s:registry.SetValidator('codefmt#EnsureFormatter')
```

If the first time we enter this, we already have extensions registered for codefmt, then the call to `SetValidator()` will end up executing `codefmt#EnsureFormatter`.  But that function doesn't yet exist, and codefmt's autoload hasn't yet finished loading, so we'll load it again, and try to loop forever:

```
Vim(call):E132: Function call depth is higher than 'maxfuncdepth'
```

In practice, you can trigger this by installing codefmt, adding an extension via Maktaba, and then running (e.g.) `:FormatCode`, which triggers the autoload.

The simple solution is to move the `SetValidator()` call down to after where `EnsureFormatter()` has been defined (and remove `s:plugin_root`, which is unused).  However, I wonder whether we should instead call `SetValidator()` from `instant/register.vim` or similar?  It seems odd that we'd defer setting up the validator until the first call to a `codefmt#` function.

(This also means that the default formatters won't be registered until that first call, though that's not actually observable, since they're always lower-priority that ones added externally.)

**Comment by dbarnett** [comment]
Putting it in a `plugin/register.vim` file SGTM. Doesn't need to be configured before plugin time, but it's weird not getting the warning for invalid formatters by the time vim finishes startup.
