### ISSUE TITLE
Add formatter for Java

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#43]
Codefmt should have support for formatting Java source code if/when a Java formatting tool exists.

It's possible something hacky could be done to organize Java imports without any kind of full-fledged Java formatting tool.

**Comment by fowles** [comment]
clang-format grew this and I will add it in shortly.
http://llvm.org/releases/3.6.0/tools/clang/docs/ReleaseNotes.html

**Comment by malcolmr** [comment]
We might also look at adding support for [google/google-java-format](https://github.com/google/google-java-format), which I see is now available, though perhaps only in the early stages (it doesn't seem to be terribly easy to get a binary to run).

**Comment by dbarnett** [comment]
Forked google-java-format to #51 so we can mark this fixed once we have at least one formatter for Java.
