### ISSUE TITLE
Repeat behavior is unexpected and, well, annoying

### ISSUE THREAD

**Issue by luan** [google/vim-codefmt#45]
Say you have `:AutoFormatBuffer` enabled and you're editing file. Then you change a line, save it, because why not. You then go to another line and hit `.` to replay that change, it reformats the code.
In my opinion it's pretty clear that the behavior is weird in this situation. I honestly don't see when having code formatting be something that is repeatable via `.` is useful but I'd be interested to hear the reasoning behind it.

https://github.com/google/vim-codefmt/blob/master/autoload/codefmt.vim#L450

I'd send a PR removing that or making it configurable, but I though I'd open a conversation first.
What do y'all think?

**Comment by dbarnett** [comment]
If the format-on-save is replaying with `.`, I'd call that a bug. Are you saying that's what's happening, or are you formatting explicitly before hitting dot?

As far as whether it's useful at all, it's probably a fringe feature. I think it least when formatting via mappings it's theoretically useful, like "format this code block" and then see another block you want formatted and hit `.` to format that as well. I guess text objects are the only case where it really seems useful to me, though. I can't imagine any scenario where I'd expect to format N lines, move the cursor, and then repeat.

**Comment by fowles** [comment]
I agree that AutoFormatBuffer should not repeat, but I think an explicit format command should (and I use that ability)

**Comment by luan** [comment]
I agree with the both of you. and yes `AutoFormatBufffer` currently repeats.

**Comment by fowles** [comment]
If you send the PR, we will be happy to merge it in (modulo signing the google contribution form)

**Comment by luan** [comment]
Sending the PR and closing this for now.
