### ISSUE TITLE
Add formatter for Bazel BUILD files

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#47]
Codefmt should have support for formatting Bazel BUILD files and *.bzl files if/when a tool for formatting Bazel files is publicly available.

**Comment by hang-qi** [comment]
And the formatter is available now: https://github.com/bazelbuild/buildifier

**Comment by achew22** [comment]
Would it be possible to export the internal code that enables this?

**Comment by dbarnett** [comment]
Yeah, that's pretty much all there is to this task. Should be pretty straightforward, just needs the notes about how to install buildifier outside Google and a little consideration for making sure we cut over to the new copy cleanly.

**Comment by Kashomon** [comment]
Added with https://github.com/google/vim-codefmt/pull/76.

**Comment by achew22** [comment]
Thanks @Kashomon! You da' bomb
