### ISSUE TITLE
Add google-java-format formatter for Java

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#51]
Codefmt should implement a [google/google-java-format](https://github.com/google/google-java-format) formatter to be used on projects that follow [Google's Java style guide](http://google-styleguide.googlecode.com/svn/trunk/javaguide.html) such as [google/truth](https://github.com/google/truth).

**Comment by dbarnett** [comment]
There's a question of default formatter precedence here. It would be nice to avoid using clang-format to format Java code in projects like google-truth even if the user has it configured as the default everywhere else. But how can codefmt know which projects have special formatting rules w/o a long list of manual mappings?

**Comment by fowles** [comment]
codefmt allows you to set things based on path yes?

**Comment by dbarnett** [comment]
Yes. The big question here is what should happen if you do:
```vim
autocmd FileType java AutoFormatBuffer
```
and then edit and save files in a project that uses Google style. If we give precedence to the clang-format formatter (which is reasonable given that google-java-format is a special case for Google projects), then clang-format will be applied. Users could tweak the settings for their known Google projects, but that's hit-or-miss, especially for Googlers who will probably want google-java-format to take precedence by default.

**Comment by Kashomon** [comment]
re: @dbarnett 

I think it's sufficient to just recommend being explicity about autocmds:

```VimL
autocmd FileType java AutoFormatBuffer google-java-format
```
