### ISSUE TITLE
Consider using -sort-includes for clang-format

### ISSUE THREAD

**Issue by malcolmr** [google/vim-codefmt#57]
I notice that clang-format has just added a `-sort-includes` option (presumably to what will become clang-format 3.8, but we should verify that); see http://llvm.org/viewvc/llvm-project?view=revision&revision=248367.

This is passed by default by clang-format's own example (Python-based) integration (which we don't use). We should work out whether include sorting (assuming you format that region) is something that makes sense to enable by default. (Yes?)

We probably want to wait until clang-format 3.8 is actually out before adding this, though.

**Comment by dbarnett** [comment]
Yeah, I'd share whatever defaults clang-format.py has, but we could definitely have an option to disable if not all users want that behavior.

**Comment by malcolmr** [comment]
I wonder if it might be reasonable to add a `clang_format_extra_arguments` flag? That would allow people who already have the (as yet unreleased) clang-format installed to pass in arguments like this one, and would also allow specifying options like -fallback_style, which we don't have any way to specify at present.

**Comment by dbarnett** [comment]
We already do version detection on the clang-format executable. We could tell if `-sort-includes` is supported at no extra charge.

`extra_arguments` is a pretty normal pattern and wouldn't be a bad idea to add regardless, but we would have the potential for built-in args clashing with users args and stuff like that. The arguments wouldn't be conditional on having a new enough clang-format version that way, but I guess users would generally be fine versioning their config together with their locally-installed version of clang-format.
