### ISSUE TITLE
clang-format should run against .ts files

### ISSUE THREAD

**Issue by achew22** [google/vim-codefmt#72]
clang-format supports ts files (formatted like js files). Would it be possible to add it as a file type?

**Comment by dbarnett** [comment]
Sounds reasonable to me. It's just a matter of adding it to the list of filetypes in the check at https://github.com/google/vim-codefmt/blob/3e72b4e85c6a0f7841dcacc9199c602c6bbc707a/autoload/codefmt.vim#L191, and then updating related comments and regenerating docs.
