### ISSUE TITLE
Consider reverting b2277e9 due to performance impact

### ISSUE THREAD

**Issue by malcolmr** [google/vim-codefmt#80]
In b2277e9, @Kashomon split out all the plugins into different files, which is great for readability, but not so great for loading time.

Locally, my vim startup time (measured using `time vim -c ':quit'`) increases from about 875ms to 935ms as a result of this change (+60ms mean, 95%CI +24ms to +94ms, N=13).

60ms isn't much, but I'm not sure it's really worthwhile?

**Comment by Kashomon** [comment]
That's... really sad. =(.  I'm confused what's so non-performant, since I adding less than 10 files.

**Comment by malcolmr** [comment]
The first time you call into any given autoload file, Vim has to try each
entry in `&rtp` to find the file.

I suspect this is the problem: that change adds an additional 7 files to
read; if codefmt is the sixth entry in `&rtp` (in my case, I suspect it's a
lot later), that's an additional 42 open() calls, perhaps on slow
filesystems.

(Alternatively, Vim may have a per-file overhead when parsing. Either way,
it's significant.)

I might retry that measurement with my home vimrc.

**Comment by dbarnett** [comment]
Yeah, really disappointing but I guess not too hard to explain in retrospect.

Is there anything about the overall AddExtension pattern that we could change to help avoid that pitfall? I could see maybe passing autoload initializer functions by name so they could be resolved late; kinda heavy conceptually, though?

I feel like there should be a way to get the best of both instead of zooming in too much on this one change as "bad". But it is hard to justify a significant, repeatable performance hit for code organization.

**Comment by malcolmr** [comment]
Actually, I probably presented the worst-case above (`&rtp` has 47 directories, some of which are on networked storage).

That's not actually representative of what I'd normally see at work (same length `&rtp`, but on local HDD) - it's an artefact of the way I'm testing this. By comparison, my normal work setup (same vimrc) loads in 390ms, not 875ms. So at worst, perhaps this change would be +30ms in practice?

On my home desktop (SSD, 15 directories in `&rtp`), I'm struggling to see any difference at all: _perhaps_ +1ms from a base of 150ms, though even that measurement's a bit sketchy.

Anyone else able to confirm whether this has a material impact or not?

**Comment by malcolmr** [comment]
And no, I can't think of a better way to do this: we want the registered `dict` at registration time for validation, so the best we could do would be to out-of-line the various `Format*` functions' bodies by adding a call-by-name trampoline. But I'm not sure that would be particularly more readable.

**Comment by Kashomon** [comment]
phew, so maybe my change isn't a huge problem.

**Comment by malcolmr** [comment]
Okay, at work, using local files rather than ones on a network, my vim startup time (measured again using `time vim -c ':quit'`) increases from about 555ms to 565ms as a result of this change (+10ms mean, 95%CI +1ms to +20ms, N=15).

I don't think +10ms is actually worth worrying about here, so closing.
