### ISSUE TITLE
Formatting *.BUILD files

### ISSUE THREAD

**Issue by RenatoUtsch** [google/vim-codefmt#82]
Hello,

I have *.BUILD files in my repository which are BUILD files implemented for dependencies to my bazel-built project (For example, jpeg.BUILD for building libjpeg). I have the following line set up in my vimrc:

```vimscript
augroup autoformat_settings
  autocmd FileType bzl AutoFormatBuffer buildifier
  " ...
augroup END
```

This works for formatting BUILD files, but if I have a file with the name following the *.BUILD convention for third party builds the file is not automatically formatted. Even more, if I run `:FormatCode` in the file, the following message is printed:

```
Not available, codefmt doesn't have a default formatter for this buffer.
```

I have to use `:FormatCode buildifier` directly for it to work.

How can I specify the default formatter for *.BUILD files?

**Comment by RenatoUtsch** [comment]
Solved this by adding this to my vimrc:

```
au BufRead,BufNewFile *.BUILD set filetype=bzl
```

**Comment by dbarnett** [comment]
I'd recommend reporting that at https://github.com/bazelbuild/vim-ft-bzl/issues if it's a known convention, and then those changes can be upstreamed into vim.

What's the use case for `*.BUILD`, though? Where is this libjpeg repo w/ this jpeg.BUILD file? AFAIK bazel wouldn't pay attention to a file like that and it wouldn't really be a "BUILD file".

**Comment by RenatoUtsch** [comment]
When you create a `new_git_repository` or a `new_http_archive` you have to
specify a BUILD file that will be used to build the third party project
(because it does not have one). This BUILD file is not part of your
project, and it is treated as if it was a BUILD file inside the root of the
third party project. Because of this, it does not make sense to call it
BUILD.

In TensorFlow and many rules_* repositories from Bazel the convention is to
call these BUILD files `<name_of_project>.BUILD`. For example:

https://github.com/tensorflow/tensorflow/blob/master/third_party/jpeg/jpeg.BUILD

This is the BUILD file used to build libjpeg, specified in a
`new_http_archive` workspace rule.

I'll report it to vim-ft-bzl, thanks!
