### ISSUE TITLE
Error formatting file: ERROR(ShellError): Error running: clang-format --version

### ISSUE THREAD

**Issue by qingzew** [google/vim-codefmt#84]
when I run `:Formatcode`, it turns out:
> Error formatting file: ERROR(ShellError): Error running: clang-format --version

```
[root@fe4524cdab25 ~]# clang-format -version
LLVM (http://llvm.org/):
  LLVM version 3.4.2
  Optimized build.
  Built Dec  7 2015 (09:37:36).
  Default target: x86_64-redhat-linux-gnu
  Host CPU: x86-64
```

**Comment by malcolmr** [comment]
The error message has two hyphens. Does `--version` work? (and what's the exit code?)

fwiw, my clang-format output is pretty different to yours, though I don't think that should matter:

```
$ clang-format-3.5 --version; echo $?
Debian clang-format version 3.5.2-3~bpo8+2 (tags/RELEASE_352/final) (based on LLVM 3.5.2)
0
```

**Comment by qingzew** [comment]
@malcolmr 
```
[root@fe4524cdab25 ~]# clang-format --version
LLVM (http://llvm.org/):
  LLVM version 3.4.2
  Optimized build.
  Built Dec  7 2015 (09:37:36).
  Default target: x86_64-redhat-linux-gnu
  Host CPU: x86-64
```

it's the same, it's the matter of clang?, mine is 3.4.2 on docker container of cnetos 7

**Comment by malcolmr** [comment]
What's the exit code after you run `clang-format`? (The `$?` in my example above.) The most obvious way I could see this error happening is if `clang-format --version` exited with a non-zero exit code in the past, though I would be surprised if that were the case.

Alternatively, you might be able to produce something useful by starting Vim with `vim -V9vim.log`, triggering the problem, and quitting. That will write a log to `vim.log`, and we could then take a look at whether there's anything useful in that output.

**Comment by qingzew** [comment]
@malcolmr  you are right
```
[root@930b00c097da ~]# clang-format --version; echo $?
LLVM (http://llvm.org/):
  LLVM version 3.4.2
  Optimized build.
  Built Dec  7 2015 (09:37:36).
  Default target: x86_64-redhat-linux-gnu
  Host CPU: x86-64
1
```

**Comment by shuaisilun** [comment]
Could you post how to solve this ? I have the same issue.

**Comment by keloyang** [comment]
mv /usr/bin/clang-format  /usr/bin/clang-format-origin
then edit /usr/bin/clang-format with the followning
```
#!/bin/bash

clang-format-origin $@
exit 0
```

**Comment by dbarnett** [comment]
That's a pretty extreme workaround. If you're doing aggressive hacks anyway you can try passing a 0 for `throw_errors` in `Syscall.Call([throw_errors])` in the plugin code, so change:
  maktaba#syscall#Create([l:executable, '--version']).Call().stdout
to
  maktaba#syscall#Create([l:executable, '--version']).Call(0).stdout

Someone should also report a bug to clang-format that their tool is misbehaving.

**Comment by dbarnett** [comment]
@shuaisilun @qingzew I sent a fix as a PR if you're interested in checking it out to verify that version solves your problems.
