### ISSUE TITLE
Wrong formatting with variable declaration

### ISSUE THREAD

**Issue by Xiaomu0** [google/vim-codefmt#85]
When I wrote
```c++
auto p[4] = something;
```
and
```c++
auto *p[4] = something;
```
Everything seems ok.

But when i wrote
```c++
auto (*p)[4] = something;
```
and then ```:FormatCode```, it comes to
```c++
auto(*p)[4] = something;
```
The "auto" can be replaced with "int", "char" and etc.

I think in ```auto (*p)``` the ```auto``` may be treated as a function name followed with a pair of brackets. Is that true? And how can I avoid it?

**Comment by malcolmr** [comment]
fwiw, I actually see the reverse (`auto(*p)` is changed to `auto (*p)`). In any case, I think this is probably a question for LLVM: `FormatCode` just calls out to `clang-format` for `cpp` filetypes (as this is).

You might want to take a look at https://clang.llvm.org/docs/ClangFormatStyleOptions.html; in particular, I wonder if the `PointerAlignment` or `DerivePointerAlignment` options are relevant here (the latter means that `clang-format` will determine whether to use `int *p` or `int* p` depending on the convention in the rest of the file - which seems similar to what you're seeing here).

**Comment by Xiaomu0** [comment]
I know that it calls out to clang-format, and what I want is a google-c++-stytle formatting.(I am sticked to google-c++-style) So I leave all config file of vim-codefmt as default, and ```auto (*p)[4]``` changed to ```auto(*p)[4]``` happend. I wonder if vim-codefmt's default style for cpp is google-style.

As for ```int *p``` or ```int* p```, I think my config(default) is for the fisrt one, because ```auto *p[4] = something;``` won't change after ```:FormatCode```, just as I mentioned above.

And by the way, if ```PointerAligment``` is the matter, could you tell me how(or where) can I change ```PointerAligment```(and other options possible) for ```:FormatCode``` to calls out clang-format? I am not good at vim-script....

Anyway, thanks for your reply. @malcolmr

**Comment by Xiaomu0** [comment]
I know that it calls out to clang-format, and what I want is a google-c++-stytle formatting.(I am sticked to google-c++-style) So I leave all config file of vim-codefmt as default, and ```auto (*p)[4]``` changed to ```auto(*p)[4]``` happend. I wonder if vim-codefmt's default style for cpp is google-style.

As for ```int *p``` or ```int* p```, I think my config(default) is for the fisrt one, because ```auto *p[4] = something;``` won't change after ```:FormatCode```, just as I mentioned above.

And by the way, if ```PointerAligment``` is the matter, could you tell me how(or where) can I change ```PointerAligment```(and other options possible) for ```:FormatCode``` to calls out clang-format? I am not good at vim-script....

Anyway, thanks for your reply. @malcolmr
