### ISSUE TITLE
Add a global version of `NoAutoFormatBuffer`

### ISSUE THREAD

**Issue by voithos** [google/vim-codefmt#87]
`:NoAutoFormatBuffer` works great when I need to temporarily disable auto-formatting for a particular file or a small config, etc, but sometimes I'm working in a another project temporarily (perhaps trying to fix a bug) and I'd really like to be able to turn auto-formatting off completely - both for the current buffer, and any new buffers that I open in the Vim session.

Ideally, there'd be a similar toggle (perhaps `:NoAutoFormatGlobal`, or something, so that the first completion still ends up being the more-commonly used `:NoAutoFormatBuffer`?).

**Comment by dbarnett** [comment]
To clarify, your situation is that you define a bunch of `autocmd FileType` rules in your .vimrc to enable it, but then sometimes you decide you want to disable it, right?

codefmt doesn't have any built-in mechanism to globally *enable*, so there'd be some awkwardness if we tacked on a mechanism to globally disable. You could create a quick-and-dirty command to do that for yourself in your vimrc, something like
```vim
command NoAutoFormatGlobal autocmd! autoformat_settings
```
(if you defined the commands in an augroup called `autoformat_settings`). Then you'd have to kill and restart vim to get it back, or define yourself a helper to redefine them.

If you're regularly wanting to disable it on certain special code paths, I'd suggest modifying the autocmd configuration to check the current filename and blacklist paths to avoid (or whitelist paths to enable formatting for). Example:
```vim
augroup autoformat_settings
  autocmd FileType go if s:ShouldAutoFormatPath() | AutoFormatBuffer gofmt | endif
augroup END
function s:ShouldAutoFormatPath() abort
  return expand('%:p') !~# '\V/some/path/'
endfunction

**Comment by voithos** [comment]
Oh! That's right, I forgot that vim-codefmt doesn't actually set up any autocmds itself, oops. This should be straightforward to do myself, then. Thanks!
