### ISSUE TITLE
Formatter "buildifier" is not available

### ISSUE THREAD

**Issue by mapx** [google/vim-codefmt#88]
`buildifier` is installed via `go get github.com/bazelbuild/buildtools/buildifier` to `~/go/bin/`.

In `~/.bashrc`:
`export PATH="~/go/bin:$PATH"` is added. I checked `which buildifier` and it is there.

However, when I `:FormatCode` a `BUILD` file, vim still reports:

> Formatter "buildifier" is not available. Setup instructions: Install buildifier.

May I know how to make it work? Thanks.

BTW, `yapf` is installed to a virtual environment and it is recognized.

**Comment by mapx** [comment]
I found `Glaive codefmt buildifier_executable='~/go/bin/buildifier'` does not work either.

While `Glaive codefmt buildifier_executable='/home/some_user/go/bin/buildifier'` works.

**Comment by dbarnett** [comment]
Check `:echo $PATH` in vim. It's possible you hadn't restarted the terminal vim was running in after you updated `$PATH`?

It's just checking `executable(YOURPATH)` in vim, so if you can get `:echo executable('buildifier')` to work then the formatter should be listed as available.

Indeed vim doesn't expand path shortcuts like `~` in the standard filename checks. I guess we could probably make that work by running the path through `expand()`, if you want to report an issue for that misfeature in particular.

**Comment by mapx** [comment]
@dbarnett Thanks for your reply!

It would be a great enhancement if the path could be expanded, though users may not realize how much work you have done to adapt the plugin to different use cases. Maybe it's an issue of vim.

I got the knowledge from you that I should set a full path somewhere to make formatters work :)

**Comment by dbarnett** [comment]
No reason the default w/o full path shouldn't work fine for you, too. But full path is a fine workaround.
