### ISSUE TITLE
Add support for shell/bash via shfmt

### ISSUE THREAD

**Issue by mvdan** [google/vim-codefmt#94]
Which can be installed via `go get -u mvdan.cc/sh/cmd/shfmt`.

The tool works in a very similar way to `gofmt`, so I figure that it would be simple to add support for it. Happy to help with any issues that may arise with it.

**Comment by infokiller** [comment]
@malcolmr WDYT? will you merge a PR that adds this?

**Comment by malcolmr** [comment]
Sure, seems reasonable.
